import os
import pandas as pd
from PIL import Image
import exifread
import pytesseract
import matplotlib.pyplot as plt
import langid
import streamlit as st
from io import BytesIO
from datetime import datetime

pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files\Tesseract-OCR\tesseract.exe"

st.set_page_config(page_title="Image Metadata Analysis", layout="wide")
st.title("Image Metadata Analysis")

uploaded_files = st.file_uploader("Upload images", type=["jpg","jpeg","png","bmp","tiff"], accept_multiple_files=True)
if not uploaded_files:
    st.info("Upload one or more images to begin.")
    st.stop()

def extract_gps(tags):
    def conv(values, ref):
        d, m, s = [float(v.num)/float(v.den) for v in values]
        coord = d + m/60.0 + s/3600.0
        if ref in ['S','W']:
            coord *= -1
        return coord
    lat = lon = None
    if "GPS GPSLatitude" in tags and "GPS GPSLongitude" in tags:
        lat = conv(tags["GPS GPSLatitude"].values, str(tags["GPS GPSLatitudeRef"]))
        lon = conv(tags["GPS GPSLongitude"].values, str(tags["GPS GPSLongitudeRef"]))
    return lat, lon

def analyze_metadata(info):
    issues = []
    if info["datetime_original"] != "Not available" and info["datetime_modified"] != "Not available":
        try:
            dt_o = datetime.strptime(info["datetime_original"], "%Y:%m:%d %H:%M:%S")
            dt_m = datetime.strptime(info["datetime_modified"], "%Y:%m:%d %H:%M:%S")
            if dt_m < dt_o:
                issues.append("Modified date earlier than original")
        except:
            pass
    if info["datetime_original"] != "Not available" and info["datetime_digitized"] != "Not available":
        if info["datetime_original"] != info["datetime_digitized"]:
            issues.append("Original and digitized timestamps differ")
    if info["software"] != "Not available":
        s = info["software"].lower()
        if any(k in s for k in ["photoshop", "gimp", "snapseed", "lightroom"]):
            issues.append("Editing software detected")
    if info["device_make"] == "Not available" and info["device_model"] == "Not available":
        issues.append("Device information missing")
    if info["GPSLink"] == "Not available" and info.get("gps_altitude","Not available") == "Not available":
        issues.append("Location data missing")
    return " | ".join(issues) if issues else "No anomalies detected"

def detect_ai_generated(info):
    ai_indicators = ["stablediffusion", "dall-e", "midjourney", "ai generated", "artbreeder", "deepai", "generated by"]
    fields = [str(info.get("software","")).lower(), str(info.get("device_make","")).lower(), str(info.get("device_model","")).lower()]
    if any(any(ind in f for ind in ai_indicators) for f in fields):
        return "Likely AI-generated"
    if info["device_make"] == "Not available" and info["device_model"] == "Not available" and info["software"] != "Not available":
        return "Possibly AI-generated"
    return "No indication"

def style_summary(val):
    if val == "No anomalies detected":
        return "color: green; font-weight: bold;"
    elif "detected" in val.lower() or "differ" in val.lower() or "earlier" in val.lower():
        return "color: red; font-weight: bold;"
    elif "missing" in val.lower():
        return "color: orange; font-weight: bold;"
    return ""

records = []
gps_points = []

for file in uploaded_files:
    try:
        img = Image.open(file)
        info = {
            "filename": file.name,
            "format": img.format,
            "mode": img.mode,
            "width": img.width,
            "height": img.height,
            "filesize_bytes": len(file.getvalue())
        }
        tags = exifread.process_file(file, details=False)
        info["device_make"] = str(tags.get("Image Make", "Not available"))
        info["device_model"] = str(tags.get("Image Model", "Not available"))
        info["lens_model"] = str(tags.get("EXIF LensModel", "Not available"))
        info["software"] = str(tags.get("Image Software", "Not available"))
        info["datetime_original"] = str(tags.get("EXIF DateTimeOriginal", "Not available"))
        info["datetime_digitized"] = str(tags.get("EXIF DateTimeDigitized", "Not available"))
        info["datetime_modified"] = str(tags.get("Image DateTime", "Not available"))
        info["exposure_time"] = str(tags.get("EXIF ExposureTime", "Not available"))
        info["f_number"] = str(tags.get("EXIF FNumber", "Not available"))
        info["iso_speed"] = str(tags.get("EXIF ISOSpeedRatings", "Not available"))
        info["focal_length"] = str(tags.get("EXIF FocalLength", "Not available"))
        info["exposure_program"] = str(tags.get("EXIF ExposureProgram", "Not available"))
        info["white_balance"] = str(tags.get("EXIF WhiteBalance", "Not available"))
        info["flash"] = str(tags.get("EXIF Flash", "Not available"))
        info["orientation"] = str(tags.get("Image Orientation", "Not available"))
        info["gps_altitude"] = str(tags.get("GPS GPSAltitude", "Not available"))
        info["gps_speed"] = str(tags.get("GPS GPSSpeed", "Not available"))
        info["gps_direction"] = str(tags.get("GPS GPSImgDirection", "Not available"))
        lat, lon = extract_gps(tags)
        if lat and lon:
            info["GPSLink"] = f"https://www.google.com/maps?q={lat},{lon}"
            gps_points.append((file.name, lat, lon))
        else:
            info["GPSLink"] = "Not available"
        text = pytesseract.image_to_string(img).strip()
        if text:
            info["ocr_text"] = text
            if len(text)<20:
                info["ocr_language"] = "Not available"
            else:
                lang, confidence = langid.classify(text)
                info["ocr_language"] = f"{lang} ({confidence:.2f})"
        else:
            info["ocr_text"] = "Not available"
            info["ocr_language"] = "Not available"
        info["analysis_summary"] = analyze_metadata(info)
        info["ai_generated"] = detect_ai_generated(info)
        records.append(info)
    except Exception as e:
        records.append({"filename": file.name, "error": str(e), "ocr_text":"Not available","ocr_language":"Not available","GPSLink":"Not available","analysis_summary":"Processing error","ai_generated":"Unknown"})

df = pd.DataFrame(records)
for col in ["GPSLink","ocr_text","ocr_language","analysis_summary","ai_generated"]:
    if col not in df.columns:
        df[col] = "Not available"
    else:
        df[col] = df[col].fillna("Not available")

st.subheader("Metadata Table")
styled_df = df[[
    "filename","format","width","height","filesize_bytes",
    "device_make","device_model","lens_model","software",
    "datetime_original","datetime_digitized","datetime_modified",
    "exposure_time","f_number","iso_speed","focal_length",
    "exposure_program","white_balance","flash","orientation",
    "gps_altitude","gps_speed","gps_direction",
    "ocr_text","ocr_language","GPSLink","analysis_summary","ai_generated"
]].style.applymap(style_summary, subset=["analysis_summary"])
st.dataframe(styled_df, use_container_width=True)

st.subheader("Visualizations")
col1, col2 = st.columns(2)

with col1:
    st.markdown("**Image Format Distribution**")
    fig, ax = plt.subplots()
    df["format"].value_counts().plot(kind="bar", color="skyblue", ax=ax)
    st.pyplot(fig)

with col2:
    st.markdown("**File Size Distribution (KB)**")
    fig, ax = plt.subplots()
    (df["filesize_bytes"]/1024).plot(kind="hist", bins=10, color="salmon", ax=ax)
    st.pyplot(fig)

col3, col4 = st.columns(2)

with col3:
    st.markdown("**Top Resolutions**")
    df["resolution"] = df["width"].astype(str)+"x"+df["height"].astype(str)
    fig, ax = plt.subplots()
    df["resolution"].value_counts().head(10).plot(kind="bar", color="lightgreen", ax=ax)
    st.pyplot(fig)

with col4:
    st.markdown("**EXIF Presence**")
    has_exif = df.filter(like="EXIF").notna().any(axis=1).sum()
    sizes = [has_exif, len(df)-has_exif]
    fig, ax = plt.subplots()
    ax.pie(sizes, labels=["With EXIF","Without EXIF"], autopct="%1.1f%%", colors=["gold","lightgrey"])
    st.pyplot(fig)

st.subheader("Download Metadata")
csv = df.to_csv(index=False).encode('utf-8')
json_data = df.to_json(orient="records", indent=2).encode('utf-8')

st.download_button("Download CSV", data=csv, file_name="metadata.csv", mime="text/csv")
st.download_button("Download JSON", data=json_data, file_name="metadata.json", mime="application/json")

if gps_points:
    st.subheader("Detected GPS Coordinates")
    for f, lat, lon in gps_points:
        st.markdown(f"- {f}: [{lat}, {lon}](https://www.google.com/maps?q={lat},{lon})")
